/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DFS_Solving_DFS_intermediario */

#ifndef _Included_DFS_Solving_DFS_intermediario
#define _Included_DFS_Solving_DFS_intermediario
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DFS_Solving_DFS_intermediario
 * Method:    setData_c
 * Signature: (I[III[IIII[I[I)V
 */
JNIEXPORT void JNICALL Java_DFS_1Solving_00024DFS_1intermediario_setData_1c
  (JNIEnv *, jobject, jint, jintArray, jint, jint, jintArray, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     DFS_Solving_DFS_intermediario
 * Method:    k_dfs_intermediario
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_DFS_1Solving_00024DFS_1intermediario_k_1dfs_1intermediario
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     DFS_Solving_DFS_intermediario
 * Method:    dfs_final
 * Signature: (I[I[III[I[II)V
 */
JNIEXPORT void JNICALL Java_DFS_1Solving_00024DFS_1intermediario_dfs_1final
  (JNIEnv *, jobject, jint, jintArray, jintArray, jint, jint, jintArray, jintArray, jint);

/*
 * Class:     DFS_Solving_DFS_intermediario
 * Method:    getQTSolutions
 * Signature: ([I)
 */
JNIEXPORT jintArray JNICALL Java_DFS_1Solving_00024DFS_1intermediario_getQTSolutions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
