/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DFS_Solving */
#include "DFS_Solving.h"

/*
 * Class:     DFS_Solving_DFS_intermediario
 * Method:    setData_c
 * Signature: (I[III[IIII[I[I)V
 */
JNIEXPORT void JNICALL Java_DFS_1Solving_00024DFS_1intermediario_setData_1c
  (JNIEnv *env, jobject jobj, jint N, jintArray mat, jint nivelP, jint nivelD, jintArray path, jint nPreFix, jint qtd_segundo_dfs, 
   jint qtd_locais, jintArray qtd_sols, jintArray melhor_sol){
    
   jint *m = (*env)->GetIntArrayElements(env, mat, 0);
   jint *path_h = (*env)->GetIntArrayElements(env, path, 0);
   jint *qtd_sols_h = (*env)->GetIntArrayElements(env, qtd_sols, 0);
   jint *melhor_sol_h = (*env)->GetIntArrayElements(env, melhor_sol, 0);
   printf("SETDATA antes");
   setData_c(N, m, nivelP, nivelD, path_h, nPreFix, qtd_segundo_dfs, qtd_locais, qtd_sols_h, melhor_sol_h);
    
  }

/*
 * Class:     DFS_Solving_DFS_intermediario
 * Method:    k_dfs_intermediario
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_DFS_1Solving_00024DFS_1intermediario_k_1dfs_1intermediario
  (JNIEnv *env, jobject jobj, jint n_blocks, jint block_size){
    k_dfs_intermediario(n_blocks, block_size);
  }

/*
 * Class:     DFS_Solving_DFS_intermediario
 * Method:    dfs_final
 * Signature: (I[I[III[I[II)V
 */
JNIEXPORT void JNICALL Java_DFS_1Solving_00024DFS_1intermediario_dfs_1final
  (JNIEnv *env, jobject jobj, jint a, jintArray b, jintArray c, jint d, jint e, jintArray f, jintArray g, jint h){}

/*
 * Class:     DFS_Solving_DFS_intermediario
 * Method:    getQTSolutions
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_DFS_1Solving_00024DFS_1intermediario_getQTSolutions
  (JNIEnv *env, jobject jobj, jintArray result_h){
    jint *result = (*env)->GetIntArrayElements(env, result_h, 0);
    return (jintArray) getResult(result);
  }
