/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EnumAccel */

#ifndef _Included_EnumAccel
#define _Included_EnumAccel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EnumAccel
 * Method:    setData
 * Signature: ([IIII[SI)I
 */
JNIEXPORT jint JNICALL Java_EnumAccel_setData
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jshortArray, jint);

/*
 * Class:     EnumAccel
 * Method:    getResult
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_EnumAccel_getQTSol
  (JNIEnv *, jobject);

  /*
 * Class:     EnumAccel
 * Method:    getResult
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_EnumAccel_getSolO
  (JNIEnv *, jobject);
/*
 * Class:     EnumAccel
 * Method:    clearAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_EnumAccel_clearAll
  (JNIEnv *, jobject);
  
JNIEXPORT void JNICALL Java_EnumAccel_00024Unit_createStream
  (JNIEnv *, jobject, jint);

/*
 * Class:     EnumAccel_Unit
 * Method:    callCompleteEnumUnits
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_EnumAccel_00024Unit_callCompleteEnumUnits
  (JNIEnv *, jobject, jint);
#ifdef __cplusplus
}
#endif
#endif
