/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MultiAccel_Calc */

#ifndef _Included_MultiAccel_Calc
#define _Included_MultiAccel_Calc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MultiAccel_Calc
 * Method:    multiplyCall
 * Signature: ([F[FIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_MultiAccel_00024Calc_multiplyCall
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     MultiAccel_Calc
 * Method:    createStream
 * Signature: (I[FII)V
 */
JNIEXPORT void JNICALL Java_MultiAccel_00024Calc_createStream
  (JNIEnv *, jobject, jint, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
