/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MultiAccel */

#ifndef _Included_MultiAccel
#define _Included_MultiAccel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MultiAccel
 * Method:    setDataCall
 * Signature: ([F[FIII)V
 */
JNIEXPORT void JNICALL Java_MultiAccel_setDataCall
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jint, jint, jint);

/*
 * Class:     MultiAccel
 * Method:    getResult
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_MultiAccel_getResult
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
