/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EnumAccel_Unit */

#ifndef _Included_EnumAccel_Unit
#define _Included_EnumAccel_Unit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EnumAccel_Unit
 * Method:    createStream
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_EnumAccel_00024Unit_createStream
  (JNIEnv *, jobject, jint);

/*
 * Class:     EnumAccel_Unit
 * Method:    callCompleteEnumUnits
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_EnumAccel_00024Unit_callCompleteEnumUnits
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
